name: Sync to s3
on:
  push:
    branches:
       - main
 jobs:
   sync:
      runs-on: ubuntu-latest
      steps:
      -name: Checkout Respository
      uses: actions/checkout@v3

      -name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY}}
        aws-region: us-east-1 #change this to your region of your bucket

      -name: sync to s3
      run: aws s3 sync . s3://appu501

      
